
trigger:
- main

variables:

  # Agent VM image name
  vmImageName: 'ubuntu-latest'


  # Project root folder. Point to the folder containing manage.py file.
  projectRoot: $(System.DefaultWorkingDirectory)

  # Python version: 3.7
  pythonVersion: '3.7'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: BuildJob
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(pythonVersion)'
      displayName: 'Use Python $(pythonVersion)'

    - script: |
        python -m venv antenv
        source antenv/bin/activate
        pip install setup
        pip install -r requirements.txt
        pip install mkdocs-material
        mkdocs build
      workingDirectory: $(projectRoot)
      displayName: "Install requirements"

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(projectRoot)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      displayName: 'Upload package'
      artifact: drop

    - task: AzureStaticWebApp@0
      inputs:
        app_location: "/"
        api_location: ""
        output_location: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip"
        azure_static_web_apps_api_token: '1a3c484ffd692a55bbe63311134d39a864d92532610b4b19ab6d93fd6af94a5f2-9d8b7ac9-b749-4195-98bc-6ec9e30fa226010148872'
